### ISSUE TITLE
HSR ToDo

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_hsr#3]
## Generic things to do
- [ ] setup a simulator (4 hours)
- [ ] upgrade to 16.04 or run the simulator in a docker container (8 hours)
- [ ] configuration (launch file structure, robot model, standardize topics) (32 hours)
- [ ] world model (port ed, remove rgbd) (4 hours, + same as AMIGO)
- [ ] navigation (reimplement or port?) (24 hours)
- [ ] text to speech (4 hours)
- [ ] speech recognition (12 hours)
- [ ] head_ref (4 hours)
- [ ] how to run `image_recognition`, `openface` and `openpose` (same as AMIGO + TX2 install in HSR)

92 hours only for HSR

## Skill layer, option redesign
- [ ] action_server/gpsr (???)
- [ ] write new generic state machines & challenges, possibly in flexbe (48 hours)
- [ ] (optional) compatibility robot object (???)

48 hours

## Skill layer, hacky compatibility layer, re-implement bodypart if back-end is different
- [ ] robot skills

32 Hours

# Total

- Total redesign: 160 hours
- Total compatibility hacky: 100 Hours

**Comment by reinzor** [comment]
Estimate: 4 months for two persons

**Comment by jlunenburg** [comment]
First: get simulator up-and-running

- Simulation
- Grasping
- Documentation
- Debugging --> get rid of all AMIGO assumptions

Total time per month per person: 4 Tuesdays and 1 Saterday --> 20 hours/month

Can we upgrade HSR to 16.04

**Comment by Rayman** [comment]
I updated the issue

**Comment by LoyVanBeek** [comment]
I've been busy getting the simulator up and running in a Docker image.
So far so good, but I couldn't push the Dockerfile to gitlab of the HSR. So, all the files are still on the PC I work on (but in git). The git log has a bunch of TODO's for me or @KevinDang74
